<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUserActive(){
        return $this->getEntityManager()->createQuery('
            SELECT u
             FROM AppBundle:User u
             WHERE u.status = :status
        ')->setParameter('status','Active')->getResult();
    }
}
